CREATE TABLE DIM_INVENTARIO (
	CVE_ART VARCHAR(16),
	DESCR VARCHAR(40),
	LIN_PROD VARCHAR(5),
	DESC_LIN VARCHAR(20),
	STOCK_MIN DOUBLE PRECISION,
	EXIST DOUBLE PRECISION,
	COSTO_PROM DOUBLE PRECISION,
	ULT_COSTO DOUBLE PRECISION,
	TIPO_ELE VARCHAR(40),
	STATUS VARCHAR(1),
	BI_ID_REGISTRO VARCHAR(100) NOT NULL,
	BI_ID_FECHA_REGISTRO TIMESTAMP,
	CONSTRAINT PK_DIM_INVENTARIO PRIMARY KEY (BI_ID_REGISTRO)
);