CREATE TABLE TB_CLIN02 (
	CVE_LIN VARCHAR(5) NOT NULL,
	DESC_LIN VARCHAR(20),
	ESUNGPO VARCHAR(1),
	CUENTA_COI VARCHAR(28),
	STATUS VARCHAR(1),
	bi_id_registro VARCHAR(100),
	bi_id_fecha_registro timestamp,
	CONSTRAINT PK_CLIN02 PRIMARY KEY (CVE_LIN)
);