CREATE TABLE DIM_VENDEDOR (
	CVE_VEND VARCHAR(5) NOT NULL,
	STATUS VARCHAR(1),
	NOMBRE VARCHAR(30),
	COMI DOUBLE PRECISION,
	CLASIFIC VARCHAR(5),
	BI_ID_REGISTRO VARCHAR(100) NOT NULL,
	BI_ID_FECHA_REGISTRO TIMESTAMP,
	CONSTRAINT PK_DIM_VENDEDOR PRIMARY KEY (CVE_VEND)
);