-- DDL Para crear tabla de EXTRACCION de CABECERA DE FACTURAS
CREATE TABLE EXT_CABECERAFACTURAS (
	ID_DOCUMENTO VARCHAR(50),
	TIPO_DOCUMENTO VARCHAR(1),
	NUMERO_DOCUMENTO VARCHAR(20),
	ESTADO VARCHAR(20),
	CODIGO_VENDEDOR VARCHAR(5),
	FECHA_EMISION TIMESTAMP,
	FECHA_CANCELACION TIMESTAMP,
	CONDICION VARCHAR(25),
	SUBTOTAL DOUBLE PRECISION,
	DESCUENTO DOUBLE PRECISION,
	DESCUENTO_ADICIONAL DOUBLE PRECISION,
	IVA DOUBLE PRECISION,
	AJUSTE DOUBLE PRECISION,
	TOTAL DOUBLE PRECISION,
	bi_id_registro VARCHAR(100),
	bi_id_fecha_registro timestamp,
	CONSTRAINT PK_EXTCABFACT PRIMARY KEY (bi_id_registro)
);