CREATE TABLE DIM_CLIENTE (
	CLAVE VARCHAR(10) NOT NULL,
	STATUS VARCHAR(1) NOT NULL,
	NOMBRE VARCHAR(120),
	MUNICIPIO VARCHAR(50),
	PAIS VARCHAR(50),
	NACIONALIDAD VARCHAR(40),
	TELEFONO VARCHAR(1),
	CLASIFIC VARCHAR(5),
	MAIL VARCHAR(1),
	DESCUENTO DOUBLE PRECISION,
	CVE_VEND VARCHAR(5),
	BI_ID_REGISTRO VARCHAR(100) NOT NULL,
	BI_ID_FECHA_REGISTRO TIMESTAMP,
	CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (BI_ID_REGISTRO)
);