SELECT * FROM TB_FACTF02

SELECT 
	  UUID ID_DOCUMENTO
	, TIP_DOC TIPO_DOCUMENTO
	, CVE_DOC NUMERO_DOCUMENTO
	, CASE 
		WHEN STATUS = 'C' THEN 'CANCELADO' 
		WHEN STATUS = 'E' THEN 'EMITIDO'
	  END ESTADO
	, CASE
		WHEN CVE_VEND = '' THEN '    3'
		ELSE CVE_VEND
	  END CODIGO_VENDEDOR
	, FECHA_DOC FECHA_EMISION
	, FECHA_CANCELA FECHA_CANCELACION
	, CONDICION
	, CAN_TOT SUBTOTAL
	, DES_TOT DESCUENTO
	, DES_FIN DESCUENTO_ADICIONAL
	, IMP_TOT4 IVA
	, IMP_TOT2 + IMP_TOT3 AJUSTE
	, IMPORTE TOTAL	
FROM TB_FACTF02
WHERE STATUS = 'E'



	CVE_DOC IN ('18SD000F12723', '18SD000F12255', '21DS000F03661')

DELETE FROM TB_CLIE02 