SELECT * FROM TB_CLIE02

SELECT
	CLAVE,
	STATUS,
	NOMBRE,
	MUNICIPIO,
	PAIS,
	NACIONALIDAD,
	CASE WHEN TELEFONO IS NULL THEN 'N' ELSE 'S' END AS TELEFONO,
	CLASIFIC,
	MAIL,
	DESCUENTO,
	CVE_VEND
FROM TB_CLIE02
WHERE BI_ID_FECHA_REGISTRO = (SELECT MAX(BI_ID_FECHA_REGISTRO) FROM TB_CLIE02)

DELETE FROM TB_CLIE02 