SELECT * FROM TB_PAR_FACTF02

SELECT *
FROM (
	SELECT 
		CVE_DOC NUMERO_DOCUMENTO,
		NUM_PAR NUMERO_REGISTRO,
		CVE_ART CODIGO_ARTICULO,
		TIPO_PROD TIPO_PRODUCTO,
		CANT CANTIDAD,
		UNI_VENTA UNIDAD,
		COST COSTO,
		PREC PRECIO,
		(CANT * PREC) SUBTOTAL,
		TOTIMP4 IVA,
		((CANT * PREC)*(DESC1/100)) DESCUENTO,
		(((CANT * PREC) - ((CANT * PREC)*(DESC1/100))) + TOTIMP4) TOTAL
	FROM TB_PAR_FACTF02 
)
WHERE 
	NUMERO_DOCUMENTO IN ('18SD000F12723', '18SD000F12255', '21DS000F03661')

DELETE FROM EXT_DETALLEFACTURAS