SELECT 
	 DOCTOS.FECHA_DOC
	,DOCTOS.CVE_VEND
	,DOCTOS.VEN_NOMBRE
	,DOCTOS.CVE_CLPV
	,DOCTOS.CLIE_NOMBRE
	,(SUM(MONTOF))-(SUM(MONTOD)) AS VENTA_NETA
	,(SUM(UNIDADESF))-(SUM(UNIDADESD)) AS VENTA_UNI
FROM (
	SELECT 
		 PER1M.DESCRIPCION AS FECHA_DOC
		,CABDOC.CVE_VEND,VEN.NOMBRE AS VEN_NOMBRE
		,CABDOC.CVE_CLPV,CLIE.NOMBRE AS CLIE_NOMBRE
		,(COALESCE(SUM(((PARDOC.CANT*PARDOC.PREC-
			(PARDOC.CANT*PARDOC.PREC*PARDOC.DESC1)/100)-(((PARDOC.CANT*PARDOC.PREC-
			(PARDOC.CANT*PARDOC.PREC*PARDOC.DESC1)/100)*PARDOC.DESC2)/100)-((((PARDOC.CANT*PARDOC.PREC-
			(PARDOC.CANT*PARDOC.PREC*PARDOC.DESC1)/100)*PARDOC.DESC2)/100)*PARDOC.DESC3/100))),0)) AS MONTOF
		,(COALESCE(SUM(PARDOC.CANT),0)) AS UNIDADESF,0.0 AS MONTOD,0.0 AS UNIDADESD 
	FROM FACTF02 CABDOC   
	LEFT JOIN (SELECT DESCRIPCION,FECHAINI,FECHAFIN FROM PERIODOS02 WHERE TIPO = 'M') PER1M ON CABDOC.FECHA_DOC >= PER1M.FECHAINI AND CABDOC.FECHA_DOC < PER1M.FECHAFIN   
	LEFT JOIN PAR_FACTF02 PARDOC ON CABDOC.CVE_DOC = PARDOC.CVE_DOC  
	LEFT JOIN CLIE02 CLIE ON CLIE.CLAVE=CABDOC.CVE_CLPV  LEFT JOIN VEND02 VEN ON VEN.CVE_VEND=CABDOC.CVE_VEND  
	LEFT JOIN INVE02 INVE ON PARDOC.CVE_ART = INVE.CVE_ART   
	WHERE 
		((PARDOC.TIPO_ELEM='N' AND PARDOC.TIPO_ELEM='G') OR PARDOC.TIPO_PROD <> 'G' 
		AND PARDOC.TIPO_ELEM <> 'K' 
		AND CABDOC.FECHA_DOC>='01.12.2021' AND CABDOC.FECHA_DOC<='31.12.2021' 
		AND CABDOC.STATUS <> 'C')  
	GROUP BY
		 PER1M.DESCRIPCION
		,CABDOC.CVE_VEND,VEN.NOMBRE
		,CABDOC.CVE_CLPV,CLIE.NOMBRE 
	UNION ALL 
	SELECT
		 PER1M.DESCRIPCION AS FECHA_DOC
		,CABDOC.CVE_VEND
		,VEN.NOMBRE AS VEN_NOMBRE
		,CABDOC.CVE_CLPV
		,CLIE.NOMBRE AS CLIE_NOMBRE
		,0.0 AS MONTOF
		,0.0 AS UNIDADESF
		,(COALESCE(SUM(((PARDOC.CANT*PARDOC.PREC-
			(PARDOC.CANT*PARDOC.PREC*PARDOC.DESC1)/100)-(((PARDOC.CANT*PARDOC.PREC-
			(PARDOC.CANT*PARDOC.PREC*PARDOC.DESC1)/100)*PARDOC.DESC2)/100)-((((PARDOC.CANT*PARDOC.PREC-
			(PARDOC.CANT*PARDOC.PREC*PARDOC.DESC1)/100)*PARDOC.DESC2)/100)*PARDOC.DESC3/100))),0)) AS MONTOD
		,(COALESCE(SUM(PARDOC.CANT),0)) AS UNIDADESD 
	FROM FACTD02 CABDOC   
	LEFT JOIN (SELECT DESCRIPCION,FECHAINI,FECHAFIN FROM PERIODOS02 WHERE TIPO = 'M') PER1M ON CABDOC.FECHA_DOC >= PER1M.FECHAINI AND CABDOC.FECHA_DOC < PER1M.FECHAFIN   
	LEFT JOIN PAR_FACTD02 PARDOC ON CABDOC.CVE_DOC = PARDOC.CVE_DOC  
	LEFT JOIN CLIE02 CLIE ON CLIE.CLAVE=CABDOC.CVE_CLPV  
	LEFT JOIN VEND02 VEN ON VEN.CVE_VEND=CABDOC.CVE_VEND  
	LEFT JOIN INVE02 INVE ON PARDOC.CVE_ART = INVE.CVE_ART   
	WHERE 
		((PARDOC.TIPO_ELEM='N' AND PARDOC.TIPO_ELEM='G') OR PARDOC.TIPO_PROD <> 'G' 
		AND PARDOC.TIPO_ELEM <> 'K' 
		AND CABDOC.FECHA_DOC>='01.12.2021' AND CABDOC.FECHA_DOC<='31.12.2021' 
		AND CABDOC.STATUS <> 'C')  
	GROUP BY 
		 PER1M.DESCRIPCION
		,CABDOC.CVE_VEND
		,VEN.NOMBRE
		,CABDOC.CVE_CLPV
		,CLIE.NOMBRE
) DOCTOS  
GROUP BY 
	 DOCTOS.FECHA_DOC
	,DOCTOS.CVE_VEND
	,DOCTOS.VEN_NOMBRE
	,DOCTOS.CVE_CLPV
	,DOCTOS.CLIE_NOMBRE